### ISSUE TITLE
Drupal 7.x-2.2 release

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/googleanalytics#18]
[7.x-2.2](https://www.drupal.org/project/google_analytics/releases/7.x-2.2)
* [x] #2584133: Update to 7.x-2.1: Deleted obsolete custom variables....
* [x] #2584133: Update to 7.x-2.1: Deleted obsolete custom variables....
* [x] #2705565: User id feature: move user hash generation to function
* [x] #2533500: Add option to disable Colorbox tracking
* [x] #2611452: @param and @return comment doc for the code base
* [x] N/A #2581767: You need to manually upgrade the custom 'before' code snippet.
* [x] N/A #2581767: You need to manually upgrade the custom 'before' code snippet.
* [x] #2509446: Specify 'requires_jquery' => FALSE, to not load jQuery if Google Analytics is used in its basic mode
* [x] #2526434: Remove unused varibles from D7
* [x] Add missing checkboxes to admin.js
* [x] #2514384: Typo in custom dimensions description
* [x] #2355091: Add {'transport': 'beacon'} for more reliable tracking with very fast browsers exiting before tracking code finishes
* [x] Added manual JS debugging example
* [x] Changed wording of debug output
* [x] #2464339: Additional test fixes
