### ISSUE TITLE
Keep up with Drupal releases: 7.x-2.3

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/googleanalytics#19]
[7.x-2.3](https://www.drupal.org/project/google_analytics/releases/7.x-2.3)
* [x] #159865 by hass, larowlan: add JS snippets for google analytics permission
* [x] #2765571</a> by kmbremner: Correct string in admin messages tab
* [x] Correct field names
* [x] D8 backport bug
* [x] bracket
* [x] Old style arrays
* [x] #2037595</a> by hass: Tests if Custom Dimensions token form validation works.
