### ISSUE TITLE
Keep up with Drupal releases: 7.x-2.4

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/googleanalytics#20]
[7.x-2.4](https://www.drupal.org/project/google_analytics/releases/7.x-2.4)
* [x] Issue #2727007 by hass: Update javascript tracking snippet
* [x] Issue #2571481 by slydevil, hass: Locally cached file is not gzipped
* [x] Issue #2903906 by hass: Assuming /404.html is at the root of site is confusing
* [x] Issue #2693595 by hass: Password reset page may send personal data to Google Analytics
* [x] Issue #2846704 by bc, hass: Add setting for premium accounts
* [x] Issue #2861691 by pmagunia: Default UA input length on Admin form
* [x] Issue #2808067 by hass: Add test for trackDomainMode value
* [x] Issue #2808067 by jamessw: New commit overwrites fix for outbound link tracking on multidomain sites
* [x] Issue #2804553 by hass: Support new create fields 'legacyHistoryImport' and 'storage'
* [x] N/A Issue #2798221 by Kristen Pol: Cleanup minor formatting issues and typo in install file
